### ISSUE TITLE
Library not founded

### ISSUE THREAD

**Issue by hfittipaldi** [glasswalk3r/ubuntu-justched#1]
It needs the library liblinux-info-perl (>=0.6), but it can't be found. Is there any ppa that I can donwload it?

By the way: the package is called java-justched and not ubuntu-justched.

PS: I founded a debian library called libdistro-info-perl. Are they the same?

**Comment by glasswalk3r** [comment]
Strangely, there is a PPA for liblinux-info-perl... this is a explicit dependency declared for java-justched.
Try to install this PPA and let me know the results.
I also fixed the README.

**Comment by hfittipaldi** [comment]
Install the PPA was my first action. But there is no liblinux on any ubuntu repository; but as I said, there is a libdistro

**Comment by glasswalk3r** [comment]
https://launchpad.net/~glasswalk3r-yahoo/+archive/ubuntu/linux-info

**Comment by hfittipaldi** [comment]
Strange... there was no package when I did apt-get update, but I already downloaded and installed manually. Thanks.

**Comment by glasswalk3r** [comment]
Great! Thanks for providing feedback, I'll add this info to the README as well.
